trigger:
  - release/*

stages:
  - stage: Build
    jobs:
    - template: azure-pipelines-template.yml
      parameters:
        arch: "x86"

  - stage: Publish
    jobs:
    - job: RetrieveAndPublish
      pool:
        vmImage: 'windows-2019'
      steps:
      - checkout: self
        clean: true
        submodules: true

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'dfir-orc_x86'
          downloadPath: '$(Build.ArtifactStagingDirectory)'

      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'github.com_a74516b02'
          repositoryName: '$(Build.Repository.Name)'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'gitTag'
          tagPattern: '^v?[0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|rc)[0-9]+'
          isPreRelease: true
          assets: |
            $(Build.ArtifactStagingDirectory)/dfir-orc_x86/MinSizeRel/DFIR-Orc_x86.exe
            $(Build.ArtifactStagingDirectory)/dfir-orc_x86/MinSizeRel/DFIR-Orc_x86.pdb
            $(Build.ArtifactStagingDirectory)/dfir-orc_x86/MinSizeRel/FastFind_x86.exe
            $(Build.ArtifactStagingDirectory)/dfir-orc_x86/MinSizeRel/FastFind_x86.pdb
          changeLogCompareToRelease: 'lastFullRelease'
          changeLogType: 'commitBased'
