parameters:
  arch: ''

jobs:
- job: vs2022_${{ parameters.arch }}
  pool:
    vmImage: 'windows-2022'
  steps:
  - checkout: self
    clean: true
    submodules: true
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        . $(Build.SourcesDirectory)/tools/ci/build.ps1
        Build-ORC `
          -Source $(Build.SourcesDirectory) `
          -Output $(Build.SourcesDirectory)/artifacts `
          -Toolchain vs2022 `
          -Architecture ${{ parameters.arch }} `
          -Configuration Debug,MinSizeRel

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/artifacts'
      contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: dfir-orc_${{ parameters.arch }}
